title: "League of Legends First Tower Analysis"
description: "League of Legends matches analysis project for DSC 80 at UCSD"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
include:
  - assets/css/custom.css
